spring:
  profiles:
    active: unset
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  servlet:
     multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB		
app:
  localrepository: ${APP_LOCALREPOSITORY}